http:
  port: ${PORT:-8001}
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    paths: '/api/*'
  auth:
    paths: '/auth/*'
  front:
    paths: '/*'
serviceEndpoints:
  apiService:
    url: 'http://mss-api:4000'
  authService:
    url: 'http://mss-auth:8080'
  frontService:
    url: 'http://mss-front:8080'
policies:
  - cors
  - log
  - proxy
  - jwt
  - request-transformer
  - rewrite

pipelines:
  authPipeline:
    apiEndpoints:
      - auth
    policies:
      - cors:
          - action:
              origin: 'http://localhost:17003'
              credentials: true
              methods: 'HEAD,PUT,PATCH,GET,POST,DELETE'
      - rewrite:
          condition:
            name: regexpmatch
            match: ^/[^/]+(/.+)$
          action:
              rewrite: $1
      - proxy:
          action:
            serviceEndpoint: authService
      - log:
          - action:
              message: ${req.method} ${req.originalUrl}
  apiPipeline:
    apiEndpoints:
      - api
    policies:
      - cors:
          - action:
              origin: '*'
              methods: 'HEAD,PUT,PATCH,GET,POST,DELETE'
      - rewrite:
            condition:
              name: regexpmatch
              match: ^/[^/]+(/.+)$
            action:
              rewrite: $1
      - jwt:
          - action:
              secretOrPublicKey: ${JWT_SECRET}
              checkCredentialExistence: false
      - request-transformer:
          - action:
              body:
                add:
                  user: req.user
      - proxy:
          - action:
              serviceEndpoint: apiService
  frontPipeline:
    apiEndpoints:
      - front
    policies:
      - request-transformer:
          - action:
              body:
                add:
                  user: req.user
      - proxy:
          - action:
              serviceEndpoint: frontService
      - log:
          - action:
              message: ${req.method} ${req.originalUrl}
